registryItems:
  applications:
    - {webflux-projectB: nq 0}
    - {webflux-projectA: nq 0}
  instances:
    - {webflux-projectB: 1}
    - {webflux-projectA: 1}
  operationNames:
    - webflux-projectB: [/notFound, /testcase]
    - webflux-projectA: [/notFound, /testcase]
  heartbeat: []
segmentItems:
  - applicationCode: webflux-projectB
    segmentSize: 2
    segments:
      - segmentId: not null
        spans:
          - operationName: /testcase
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: /testcase}
              - {key: http.method, value: GET}
            refs:
              - {parentEndpointId: 0, parentEndpoint: /testcase, networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: '${webflux-projectA[0]}', parentServiceInstanceId: nq 0, networkAddress: 'projectB-service:18080', entryEndpoint: /testcase, entryServiceInstanceId: nq 0}
      - segmentId: not null
        spans:
          - operationName: /notFound
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: /notFound}
              - {key: http.method, value: GET}
              - {key: status_code, value: '404'}
            refs:
              - {parentEndpointId: 0, parentEndpoint: /testcase, networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 2, parentTraceSegmentId: '${webflux-projectA[0]}', parentServiceInstanceId: nq 0, networkAddress: 'projectB-service:18080', entryEndpoint: /testcase, entryServiceInstanceId: nq 0}
  - applicationCode: webflux-projectA
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /testcase
            operationId: 0
            parentSpanId: 0
            spanId: 1
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 2
            componentName: ''
            isError: false
            spanType: Exit
            peer: projectB-service:18080
            peerId: 0
            tags:
              - {key: url, value: 'http://projectB-service:18080/testcase'}
              - {key: http.method, value: GET}
          - operationName: /notFound
            operationId: 0
            parentSpanId: 0
            spanId: 2
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 2
            componentName: ''
            isError: false
            spanType: Exit
            peer: projectB-service:18080
            peerId: 0
            tags:
              - {key: url, value: 'http://projectB-service:18080/notFound'}
              - {key: http.method, value: GET}
              - {key: status_code, value: '404'}
          - operationName: /testcase
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/projectA/testcase'}
              - {key: http.method, value: GET}
