registryItems:
  applications:
    - {projectB: nq 0}
    - {projectA: nq 0}
    - {projectD: nq 0}
    - {projectC: nq 0}
  instances:
    - {projectB: 1}
    - {projectA: 1}
    - {projectD: 1}
    - {projectC: 1}
  operationNames:
    - projectB: [/projectD/test, /projectC/test, /test]
    - projectA: [/projectB/test, /test]
    - projectD: [/test]
    - projectC: [/test]
segmentItems:
  - applicationCode: projectB
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /projectC/test
            operationId: eq 0
            parentSpanId: 0
            spanId: 1
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 2
            componentName: null
            isError: false
            spanType: Exit
            peer: projectC-scenario:28080
            peerId: 0
            tags:
              - {key: url, value: 'http://projectC-scenario:28080/projectC/test'}
              - {key: http.method, value: GET}
          - operationName: /projectD/test
            operationId: eq 0
            parentSpanId: 0
            spanId: 2
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 2
            componentName: null
            isError: false
            spanType: Exit
            peer: projectD-scenario:38080
            peerId: 0
            tags:
              - {key: url, value: 'http://projectD-scenario:38080/projectD/test'}
              - {key: http.method, value: GET}
          - operationName: /test
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: null
            isError: false
            spanType: Entry
            peer: null
            peerId: 0
            tags:
              - {key: url, value: 'http://projectB-scenario:18080/projectB/test'}
              - {key: http.method, value: GET}
            refs:
              - {parentServiceId: 0, parentServiceName: /test, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: "${projectA[0]}", parentApplicationInstanceId: nq 0, networkAddress: 'projectB-scenario:18080', entryServiceName: /test, entryApplicationInstanceId: nq 0}
  - applicationCode: projectA
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /projectB/test
            operationId: 0
            parentSpanId: 0
            spanId: 1
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 2
            componentName: null
            isError: false
            spanType: Exit
            peer: projectB-scenario:18080
            peerId: 0
            tags:
              - {key: url, value: 'http://projectB-scenario:18080/projectB/test'}
              - {key: http.method, value: GET}
          - operationName: /test
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: null
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/projectA/test'}
              - {key: http.method, value: GET}
  - applicationCode: projectD
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /test
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: 'http://projectD-scenario:38080/projectD/test'}
              - {key: http.method, value: GET}
            refs:
              - {parentServiceId: 0, parentServiceName: /test, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 2, parentTraceSegmentId: "${projectB[0]}", parentApplicationInstanceId: nq 0 , networkAddress: 'projectD-scenario:38080', entryServiceName: /test, entryApplicationInstanceId: nq 0}
  - applicationCode: projectC
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /test
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: 'http://projectC-scenario:28080/projectC/test'}
              - {key: http.method, value: GET}
            refs:
              - {parentServiceId: 0, parentServiceName: /test, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: "${projectB[0]}", parentApplicationInstanceId: nq 0, networkAddress: 'projectC-scenario:28080', entryServiceName: /test, entryApplicationInstanceId: nq 0}
