registryItems:
  applications:
  - {spring-with-request-method-op-name-scenario: nq 0}
  instances:
  - {spring-with-request-method-op-name-scenario: 1}
  operationNames:
  - spring-with-request-method-op-name-scenario: [
    "/spring-with-request-method-op-name-scenario/requestmethod/acceptGetExplicit",
    "/spring-with-request-method-op-name-scenario/requestmethod/acceptAllExplicit",
    "/requestmethod/requestmethod-case",
    "{GET}/requestmethod/acceptGetExplicit",
    "{GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS,TRACE}/requestmethod/acceptAllExplicit"
  ]
segmentItems:
- applicationCode: spring-with-request-method-op-name-scenario
  segmentSize: 3
  segments:
  - segmentId: nq 0
    spans:
    - operationName: "{GET}/requestmethod/acceptGetExplicit"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: "url", value: "http://localhost:8080/spring-with-request-method-op-name-scenario/requestmethod/acceptGetExplicit"}
      - {key: "http.method", value: "GET"}
      refs:
      - {parentEndpointId: 0, parentEndpoint: "/requestmethod/requestmethod-case",
         networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 1,
         parentTraceSegmentId: '${spring-with-request-method-op-name-scenario[2]}', parentServiceInstanceId: 1,
         networkAddress: "localhost:8080", entryEndpoint: "/requestmethod/requestmethod-case",
         entryServiceInstanceId: 1}
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ""
      isError: false
      spanType: Entry
      peer: ""
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "{GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS,TRACE}/requestmethod/acceptAllExplicit"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: "url", value: "http://localhost:8080/spring-with-request-method-op-name-scenario/requestmethod/acceptAllExplicit"}
      - {key: "http.method", value: "POST"}
      refs:
      - {parentEndpointId: 0, parentEndpoint: "/requestmethod/requestmethod-case",
         networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 2,
         parentTraceSegmentId: '${spring-with-request-method-op-name-scenario[2]}', parentServiceInstanceId: 1,
         networkAddress: "localhost:8080", entryEndpoint: "/requestmethod/requestmethod-case",
         entryServiceInstanceId: 1}
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ""
      isError: false
      spanType: Entry
      peer: ""
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "/spring-with-request-method-op-name-scenario/requestmethod/acceptGetExplicit"
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Http
      tags:
      - {key: "url", value: "http://localhost:8080/spring-with-request-method-op-name-scenario/requestmethod/acceptGetExplicit"}
      - {key: "http.method", value: "GET"}
      startTime: nq 0
      endTime: nq 0
      componentId: 13
      componentName: ""
      isError: false
      spanType: Exit
      peer: "localhost:8080"
      peerId: 0
    - operationName: "/spring-with-request-method-op-name-scenario/requestmethod/acceptAllExplicit"
      operationId: 0
      parentSpanId: 0
      spanId: 2
      spanLayer: Http
      tags:
      - {key: "url", value: "http://localhost:8080/spring-with-request-method-op-name-scenario/requestmethod/acceptAllExplicit"}
      - {key: "http.method", value: "POST"}
      startTime: nq 0
      endTime: nq 0
      componentId: 13
      componentName: ""
      isError: false
      spanType: Exit
      peer: "localhost:8080"
      peerId: 0
    - operationName: "/requestmethod/requestmethod-case"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: "url", value: "http://localhost:{SERVER_OUTPUT_PORT}/spring-with-request-method-op-name-scenario/requestmethod/requestmethod-case"}
      - {key: "http.method", value: "GET"}
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ""
      isError: false
      spanType: Entry
      peer: ""
      peerId: 0
