registryItems:
  applications:
  - {hystrix-scenario: nq 0 }
  instances:
  - {hystrix-scenario: nq 0}
  operationNames:
  - hystrix-scenario: [Hystrix/FailedCommand/Execution, Hystrix/FailedCommand/Fallback, /case/hystrix-case, Hystrix/SuccessCommand/Execution]
segmentItems:
- applicationCode: hystrix-scenario
  segmentSize: 2
  segments:
  - segmentId: not null
    spans:
    - operationName: Hystrix/FailedCommand/Fallback
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 29
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /case/hystrix-case, networkAddressId: 0,entryServiceId: 0, refType: CrossThread, parentSpanId: 2, parentTraceSegmentId: '${hystrix-scenario[1]}',parentApplicationInstanceId: 0, networkAddress: '', entryServiceName: /case/hystrix-case, entryApplicationInstanceId: nq 0 }
  - segmentId: not null
    spans:
    - operationName: Hystrix/SuccessCommand/Execution
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 29
      componentName: ''
      isError: false
      spanType: Local
      peer: '',
      peerId: 0
    - operationName: Hystrix/FailedCommand/Execution
      operationId: 0
      parentSpanId: 0
      spanId: 2
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 29
      componentName: ''
      isError: false
      spanType: Local
      peer: '',
      peerId: 0
    - operationName: /case/hystrix-case
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/hystrix-case/case/hystrix-case'}
      - {key: http.method, value: GET}