version: '2.1'
services:
  zk-server:
    image: zookeeper:3.4.10

  zookeeper-scenario:
    image: skywalking/zookeeper-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "8080"
    ports:
      - "{SERVER_OUTPUT_PORT}:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:19876
      - ZK_ADDRESS=zk-server:2181
    links:
      - mock-collector
      - zk-server
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/skywalking-zookeeper-scenario/agent
    depends_on:
      - mock-collector
      - zk-server

  mock-collector:
    image: skywalking/skywalking-mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "{COLLECTOR_OUTPUT_PORT}:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5