registryItems:
  applications:
  - {spring-cloud-feign-v2-scenario: nq 0}
  instances:
  - {spring-cloud-feign-v2-scenario: 1}
  operationNames:
  - spring-cloud-feign-v2-scenario: [/case/spring-cloud-feign-v2, '/update/{id}', '/delete/{id}', '/feign-case/create/', '/feign-case/delete/1', /create/, '/get/{id}', '/feign-case/update/1','/feign-case/get/1']
segmentItems:
- applicationCode: spring-cloud-feign-v2-scenario
  segmentSize: 4
  segments:
  - segmentId: not null
    spans:
    - operationName: case/get/{userId}
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080/case/get/1'}
      - {key: http.method, value: GET}
      refs:
      - {parentEndpointId: 0, parentEndpoint: /case/spring-cloud-feign-v2,, networkAddressId: 0,
        entryEndpointId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: "${spring-cloud-feign-v2-scenario[4]}",
        parentServiceInstanceId: nq 0, networkAddress: 'localhost:8080', entryEndpoint: /case/spring-cloud-feign-v2,
        entryServiceInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: /case/send
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080/case/send'}
      - {key: http.method, value: POST}
      refs:
      - {parentEndpointId: 0, parentEndpoint: /case/spring-cloud-feign-v2,, networkAddressId: 0,
        entryEndpointId: 0, refType: CrossProcess, parentSpanId: 2, parentTraceSegmentId: "${spring-cloud-feign-v2-scenario[4]}",
        parentServiceInstanceId: 1, networkAddress: 'localhost:8080', entryEndpoint: /case/spring-cloud-feign-v2,,
        entryServiceInstanceId: 1}
  - segmentId: not null
    spans:
    - operationName: /case/delete
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080/case/delete'}
      - {key: http.method, value: DELETE}
      refs:
      - {parentEndpointId: 0, parentEndpoint: /case/spring-cloud-feign-v2,, networkAddressId: 0,
        entryEndpointId: 0, refType: CrossProcess, parentSpanId: 3, parentTraceSegmentId: "${spring-cloud-feign-v2-scenario[4]}",
        parentServiceInstanceId: 1, networkAddress: 'localhost:8080', entryEndpoint: /case/spring-cloud-feign-v2,,
        entryServiceInstanceId: 1}
  - segmentId: not null
    spans:
    - operationName: /case/update
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080//case/update'}
      - {key: http.method, value: UPDATE}
      refs:
      - {parentEndpointId: 0, parentEndpoint: /case/spring-cloud-feign-v2,, networkAddressId: 0,
        entryEndpointId: 0, refType: CrossProcess, parentSpanId: 4, parentTraceSegmentId: "${spring-cloud-feign-v2-scenario[4]}",
        parentServiceInstanceId: 1, networkAddress: 'localhost:8080', entryEndpoint: /case/spring-cloud-feign-v2,,
        entryServiceInstanceId: 1}
  - segmentId: not null
    spans:
    - operationName: /case/get/{userId}
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 11
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
      tags:
      - {key: http.method, value: GET}
      - {key: url, value: 'http://localhost:8080/case/get/1'}
    - operationName: /case/send
      operationId: 0
      parentSpanId: 0
      spanId: 2
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 11
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
      tags:
      - {key: http.method, value: POST}
      - {key: url, value: 'http://localhost:8080/case/send'}
    - operationName: /case/delete
      operationId: 0
      parentSpanId: 0
      spanId: 3
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 11
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
      tags:
      - {key: http.method, value: DELETE}
      - {key: url, value: 'http://localhost:8080/case/delete'}
    - operationName: /case/update
      operationId: 0
      parentSpanId: 0
      spanId: 4
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 11
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
      tags:
      - {key: http.method, value: PUT}
      - {key: url, value: 'http://localhost:8080/case/update'}
    - operationName: /case/spring-cloud-feign-v2
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/case/spring-cloud-feign-v2'}
      - {key: http.method, value: GET}