registryItems:
  applications:
  - {servicecomb-provider: nq 0}
  - {servicecomb-consumer: nq 0}
  instances:
  - {servicecomb-provider: 1}
  - {servicecomb-consumer: 1}
  operationNames:
  - servicecomb-consumer: [codefirstClient.codeFirstSpringmvcHello.say, codefirst.codeFirstHello.sayHi]
  - servicecomb-provider: [codefirst.codeFirstHello.sayHi]
segmentItems:
- applicationCode: servicecomb-consumer
  segmentSize: ge 1
  segments:
    - segmentId: not null
      spans:
        -
          operationName: codefirst.codeFirstHello.sayHi
          operationId: eq 0
          parentSpanId: 0
          spanId: 1
          tags:
          - {key: "url", value: /sayHi}
          logs: []
          startTime: nq 0
          endTime: nq 0
          isError: false
          spanLayer: RPCFramework
          spanType: Exit
          componentName: null
          componentId: 28
          peer: not null
          peerId: eq 0
        -
          operationName: codefirstClient.codeFirstSpringmvcHello.say
          operationId: eq 0
          parentSpanId: -1
          spanId: 0
          tags:
          - {key: "url", value: /case}
          logs: []
          startTime: nq 0
          endTime: nq 0
          isError: false
          spanLayer: RPCFramework
          spanType: Entry
          componentName: null
          componentId: 28
          peer: not null
          peerId: eq 0

- applicationCode: servicecomb-provider
  segmentSize: ge 1
  segments:      
    - segmentId: not null
      spans:
        -
          operationName: codefirst.codeFirstHello.sayHi
          operationId: eq 0
          parentSpanId: -1
          spanId: 0
          tags: 
            - {key: "url", value: /sayHi}
          logs: []
          startTime: nq 0
          endTime: nq 0
          spanLayer: null
          isError: false
          spanType: Entry
          componentName: null
          componentId: 28
          peer: null
          peerId: eq 0
          refs: 
            - {parentSpanId: 1, parentTraceSegmentId: "${servicecomb-consumer[0]}", entryEndpoint: "codefirstClient.codeFirstSpringmvcHello.say", networkAddress: not null, parentEndpoint: "codefirstClient.codeFirstSpringmvcHello.say",refType: not null,entryServiceInstanceId: nq 0 }
