registryItems:
  applications:
  - {gson-scenario: nq 0}
  instances:
  - {gson-scenario: nq 0}
  operationNames:
  - gson-scenario: [/case/gson-case]
segmentItems:
- applicationCode: gson-scenario
  segmentSize: 1
  segments:
  - segmentId: nq 0
    spans:
    - operationName: Gson/ToJson 
      operationId: 0  
      parentSpanId: 0  
      spanId: 1  
      spanLayer: Unknown 
      tags:
      - {key: 'length', value: 'not null'}
      startTime: nq 0 
      endTime: nq 0 
      componentId: 55 
      componentName: '' 
      isError: false 
      spanType: Local  
      peer: ' ' 
      peerId: 0
    - operationName: Gson/FromJson
      operationId: 0 
      parentSpanId: 0 
      spanId: 2 
      spanLayer: Unknown
      tags:
      - {key: 'length', value: 'not null'}
      startTime: nq 0 
      endTime: nq 0 
      componentId: 55 
      componentName: '' 
      isError: false 
      spanType: Local 
      peer: '' 
      peerId: 0
    - operationName: /case/gson-case
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/gson-scenario/case/gson-case'}
      - {key: http.method, value: GET}