registryItems:
  applications:
  - {jettyclient-scenario: 2}
  instances:
  - {jettyclient-scenario: 1}
  operationNames:
  - jettyclient-scenario: [/case/receiveContext-0, /case/receiveContext-0,
      /case/jettyclient-case]
  heartbeat: []
segmentItems:
- applicationCode: jettyclient-scenario
  segmentSize: 2
  segments:
  - segmentId: not null
    spans:
    - operationName: /case/receiveContext-0
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: null
      isError: false
      spanType: Entry
      peer: null
      peerId: 0
      tags:
      - {key: url, value: 'http://127.0.0.1:8080/jettyclient-case/case/receiveContext-0'}
      - {key: http.method, value: GET}
      refs:
      - {parentServiceId: 0, parentServiceName: /case/jettyclient-case, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: "${jettyclient-scenario[1]}", parentApplicationInstanceId: 1, networkAddress: '127.0.0.1:8080', entryServiceName: /case/jettyclient-case, entryApplicationInstanceId: 1}
  - segmentId: not null
    spans:
    - operationName: /case/receiveContext-0
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 18
      componentName: null
      isError: false
      spanType: Exit
      peer: 127.0.0.1:8080
      peerId: 0
      tags:
      - {key: http.method, value: GET}
      - {key: url, value: 'http://127.0.0.1:8080/jettyclient-case/case/receiveContext-0'}
    - operationName: /case/jettyclient-case
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: null
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/jettyclient-case/case/jettyclient-case'}
      - {key: http.method, value: GET}