registryItems:
  applications:
    - {hessian-consumer: nq 0}
    - {hessian-provider: nq 0}
  instances:
    - {hessian-consumer: 1}
    - {hessian-provider: 1}
  operationNames:
    - hessian-consumer: [/hessian-case/hello,/HelloService]
    - hessian-provider: ['org.apache.skywalking.plugin.hessian.service.HelloService']
segmentItems:
  - applicationCode: hessian-consumer
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /hessian-case/hello
            operationId: eq 0
            parentSpanId: -1
            spanId: 0
            startTime: nq 0
            endTime: nq 0
            spanLayer: Http
            tags:
              - {key: url, value: 'http://localhost:18080/hessian-case/hello'}
              - {key: http.method, value: GET}
            isError: false
            spanType: Entry
            componentName: null
            componentId: 1
            logs: []
            peer: null
            peerId: eq 0
          - operationName: /HelloService
            operationId: eq 0
            parentSpanId: 0
            spanId: 1
            startTime: nq 0
            endTime: nq 0
            isError: false
            spanLayer: RPCFramework
            tags:
              - {key: url, value: '/HelloService'}
            spanType: Exit
            componentName: null
            componentId: 65
            logs: []
            peer: null
            peerId: eq 0
  - applicationCode: hessian-provider
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: 'org.apache.skywalking.plugin.hessian.service.HelloService'
            operationId: eq 0
            parentSpanId: -1
            spanId: 0
            spanLayer: RPCFramework
            tags:
              - {key: url, value: 'org.apache.skywalking.plugin.hessian.service.HelloService'}
            refs:
              - {parentEndpointId: 0,parentEndpoint: "/HelloService",networkAddressId: not null,refType: CrossProcess,parentSpanId: 1,parentTraceSegmentId: not null,parentServiceInstanceId: nq 0,networkAddress: not null,entryEndpoint: "/HelloService",entryServiceInstanceId: 1}
            startTime: not null
            endTime: not null
            componentId: 65
            componentName: null
            isError: false
            spanType: Entry
            peer: null
            peerId: eq 0
