registryItems:
  applications:
    - {hessian-consumer: nq 0}
    - {hessian-provider: nq 0}
  instances:
    - {hessian-consumer: 1}
    - {hessian-provider: 1}
  operationNames:
    -  hessian-consumer: [
      "/hessian-case/HelloService"
      "/hessian-case/hello",
    ]
    - hessian-server: [
      "/hessian-case/HelloService"
    ]
segmentItems:
  - applicationCode: hessian-client
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /hessian-case/HelloService
            operationId: 0
            parentSpanId: 0
            spanId: 1
            spanLayer: RPCFramework
            startTime: nq 0
            endTime: nq 0
            componentId: 62
            componentName: ''
            isError: false
            spanType: Exit
            peer:
            peerId: 0
          - operationName: /hessian-case/hello
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            tags:
              - {key: url, value: 'http://localhost:18080/hessian-case/hello'}
              - {key: http.method, value: GET}
            startTime: nq 0
            endTime: nq 0
            componentId: 1
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
  - applicationCode: hessian-provider
    segmentSize: 1
    segments:
      - segmentId: not null
        spans:
          - operationName: /hessian-case/HelloService
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: HESSIAN
            tags:
              - {key: url, value: 'http://hessian-case:8080/hessian-case/HelloService'}
              - {key: http.method, value: POST}
            startTime: nq 0
            endTime: nq 0
            componentId: 63
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            refs:
              - {parentEndpointId: 0, parentEndpoint: /hessian-case/HelloService, networkAddressId: 0, entryEndpointId: 0,
                 refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: '${hessian-provider[0]}',
                 parentServiceInstanceId: nq 0, networkAddress: 'hessian-server:8080', entryEndpoint: /hessina-case/HelloService,
                 entryServiceInstanceId: nq 0}