registryItems:
  applications:
    - {hessian-consumer: nq 0}
    - {hessian-provider: nq 0}
  instances:
    - {hessian-consumer: 1}
    - {hessian-provider: 1}
  operationNames:
    - hessian-consumer: [org.apache.skywalking.plugin.hessian.client.service.HelloService,/hessian-case/hello]
    - hessian-provider: [org.apache.skywalking.plugin.hessian.service.HelloService]
segmentItems:
- applicationCode: hessian-consumer
  segmentSize: 1
  segments:
  - segmentId: not null
    spans:
    - operationName: org.apache.skywalking.plugin.hessian.client.service.HelloService
      operationId: 0
      parentSpanId: 0
      spanId: 1
      startTime: nq 0
      endTime: nq 0
      isError: false
      spanLayer: RPCFramework
      tags:
      - {key: url, value: org.apache.skywalking.plugin.hessian.client.service.HelloService}
      spanType: Exit
      componentName: null
      componentId: 66
      peer: null
      peerId: eq 0
    - operationName: /hessian-case/hello
      operationId: 0
      parentSpanId: -1
      spanId: 0
      startTime: nq 0
      endTime: nq 0
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/hessian-case/hello'}
      - {key: http.method, value: GET}
      isError: false
      spanType: Entry
      componentName: null
      componentId: 1
      peer: null
      peerId: eq 0
- applicationCode: hessian-provider
  segmentSize: 1
  segments:
  - segmentId: not null
    spans:
    - operationName: org.apache.skywalking.plugin.hessian.service.HelloService
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: RPCFramework
      tags:
      - {key: url, value: org.apache.skywalking.plugin.hessian.service.HelloService}
      refs:
      - {parentEndpointId: 0,parentEndpoint: "/hessian-case/hello",networkAddressId: 0,entryEndpointId: 0, refType: CrossProcess,parentSpanId: 1,parentTraceSegmentId: not null,parentServiceInstanceId: nq 0,networkAddress: ':',entryEndpoint: "/hessian-case/hello",entryServiceInstanceId: nq 0}
      startTime: not null
      endTime: not null
      componentId: 66
      isError: false
      componentName: null
      spanType: Entry
      peer:
      peerId: 0
