registryItems:
  applications:
  - {httpasyncclient-scenario: nq 0}
  instances:
  - {httpasyncclient-scenario: 1}
  operationNames:
  - httpasyncclient-scenario: [/httpasyncclient/back, /back, /front]
segmentItems:
- applicationCode: httpasyncclient-scenario
  segmentSize: 3
  segments:
  - segmentId: not null
    spans:
    - operationName: /front
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: not null
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://127.0.0.1:{SERVER_OUTPUT_PORT}/httpasyncclient/front' }
      - {key: http.method, value: GET }
  - segmentId: not null
    spans:
    - operationName: /back
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: not null
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://127.0.0.1:8080/httpasyncclient/back' }
      - {key: http.method, value: GET }
      refs:
      - {parentEndpointId: 0, parentEndpoint: httpasyncclient/local, networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: '${httpasyncclient-scenario[2]}', parentServiceInstanceId: nq 0, networkAddress: '127.0.0.1:8080', entryEndpoint: /front, entryServiceInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: /httpasyncclient/back
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: not null
      componentName: ''
      isError: false
      spanType: Exit
      peer: 127.0.0.1:8080
      peerId: 0
      tags:
      - {key: url, value: 'http://127.0.0.1:8080/httpasyncclient/back' }
      - {key: http.method, value: GET }
    - operationName: httpasyncclient/local
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: not null
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: ''
      isError: false
      spanType: Local
      peer: ""
      peerId: 0
      refs:
      - {parentEndpointId: 0, parentEndpoint: /front, networkAddressId: 0, entryEndpointId: 0, refType: CrossThread, parentSpanId: 0, parentTraceSegmentId: '${httpasyncclient-scenario[0]}',parentServiceInstanceId: 1,networkAddress: '', entryEndpoint: /front,entryServiceInstanceId: 1}
