registryItems:
  applications:
  - {lettuce-scenario: nq 0}
  instances:
  - {lettuce-scenario: 1}
  operationNames:
  - letyuce-scenario: [/sync,REDIS-Lettuce/SET,REDIS-Lettuce/GET  ]
segmentItems:
- applicationCode: lettuce-scenario
  segmentSize: 1
  segments:
  - segmentId: not null
    spans:
    - operationName: /sync
      operationId: eq 0
      parentSpanId: -1
      spanId: 0
      startTime: nq 0
      endTime: nq 0
      isError: false
      spanLayer: Http
      spanType: Entry
      componentName:
      componentId: eq 14
      tags:
        - {key: url, value: 'http://127.0.0.1:8080/sync'}
        - {key: http.method, value: GET}
      logs: []
      peer: null
      peerId: eq 0
    - operationName: REDIS-Lettuce/SET
      operationId: eq 0
      parentSpanId: 0
      spanId: 1
      startTime: nq 0
      endTime: nq 0
      spanLayer: CACHE
      isError: false
      spanType: Exit
      componentName: null
      componentId: 7
      tags:
        - {key: db.type, value: 'Redis' }
        - {key: db.statement, value: not null }
      logs: []
      peer: 127.0.0.1:6379
      peerId: eq 0
      - operationName: REDIS-Lettuce/GET
        operationId: eq 0
        parentSpanId: 1
        spanId: 2
        startTime: nq 0
        endTime: nq 0
        spanLayer: CACHE
        isError: false
        spanType: Exit
        componentName: null
        componentId: 7
        tags:
          - {key: db.type, value: 'Redis'}
          - {key: db.statement, value: not null }
        logs: []
        peer: 127.0.0.1:6379
        peerId: eq 0

