version: '2.1'
services:
  resteasy-server-scenario:
    image: skywalking/resteasy-server-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "18080"
    links:
      - mock-collector
    environment:
      - COLLECTOR_SERVER=mock-collector:19876
      - RESTEASY_PORT=18080
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/resteasy-server-scenario/agent
    depends_on:
      mock-collector:
        condition: service_healthy

  mock-collector:
    image: skyapm/mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "{COLLECTOR_OUTPUT_PORT}:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5
