registryItems:
  applications:
  - {resteasy-server-scenario: nq 0}
  instances:
  - {resteasy-server-scenario: 1}
  operationNames:
  - resteasy-server-scenario: [/case/sync]
segmentItems:
- applicationCode: resteasy-server-scenario
  segmentSize: 1
  segments:
  - segmentId: not null
    spans:
    - operationName: /case/sync
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 60
      componentName: 'RESTEasy'
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/resteasy-server-case/case/sync'}
      - {key: http.method, value: GET}