version: '2.1'
services:
  jettyserver-scenario:
    image: skywalking/jettyserver-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "18080"
    links:
      - mock-collector
    environment:
      - COLLECTOR_SERVER=mock-collector:19876
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/skywalking-jettyserver-scenario/agent
    depends_on:
      mock-collector:
        condition: service_healthy

  jettyclient-scenario:
    image:  skywalking/jettyclient-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "8080"
    ports:
      - "{SERVER_OUTPUT_PORT}:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:19876
      - JETTY_SERVER_HOST=jettyserver-scenario
    links:
      - mock-collector
      - jettyserver-scenario
    volumes:
     - {AGENT_FILE_PATH}:/usr/local/skywalking-jettyclient-scenario/agent
    depends_on:
      mock-collector:
        condition: service_healthy

  mock-collector:
    image: skyapm/mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "{COLLECTOR_OUTPUT_PORT}:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5
