registryItems:
  applications:
  - {shardingsphere-scenario: nq 0}
  instances:
  - {shardingsphere-scenario: 1}
  operationNames:
  - shardingsphere-scenario: [/case/shardingsphere-case]
  heartbeat: []
segmentItems:
- applicationCode: shardingsphere-scenario
  segmentSize: 4
  segments:
  - segmentId: not null
    spans:
    - operationName: Async/shardingsphere-case/case/receiveContext-0
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
    - operationName: /case/shardingsphere-case
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: null
      isError: false
      spanType: Entry
      peer: null
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/shardingsphere-case/case/shardingsphere-case'}
      - {key: http.method, value: GET}
  - segmentId: not null
    spans:
    - operationName: /case/receiveContext-0
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: null
      isError: false
      spanType: Entry
      peer: null
      peerId: 0
      tags:
      - {key: url, value: 'http://127.0.0.1:8080/shardingsphere-case/case/receiveContext-0'}
      - {key: http.method, value: GET}
      refs:
      - {parentServiceId: 0, parentServiceName: /shardingsphere-case/case/receiveContext-0, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 0, parentTraceSegmentId: "${shardingsphere-scenario[3]}", parentApplicationInstanceId: nq 0, networkAddress: '127.0.0.1:8080', entryServiceName: /case/shardingsphere-case, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: /case/receiveContext-1
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: null
      isError: false
      spanType: Entry
      peer: null
      peerId: 0
      tags:
      - {key: url, value: 'http://127.0.0.1:8080/shardingsphere-case/case/receiveContext-1'}
      - {key: http.method, value: GET}
      refs:
      - {parentServiceId: 0, parentServiceName: /shardingsphere-case/case/receiveContext-0, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 0, parentTraceSegmentId: "${shardingsphere-scenario[3]}", parentApplicationInstanceId: nq 0, networkAddress: '127.0.0.1:8080', entryServiceName: /case/shardingsphere-case, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: /shardingsphere-case/case/receiveContext-0
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 12
      componentName: null
      isError: false
      spanType: Exit
      peer: 127.0.0.1:8080
      peerId: 0
      tags:
      - {key: http.method, value: GET}
      - {key: url, value: 'http://127.0.0.1:8080/shardingsphere-case/case/receiveContext-0'}
      refs:
      - {parentServiceId: 0, parentServiceName: /case/shardingsphere-case, networkAddressId: 0, entryServiceId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: "${shardingsphere-scenario[0]}", parentApplicationInstanceId: nq 0, networkAddress: '', entryServiceName: /case/shardingsphere-case, entryApplicationInstanceId: nq 0}
