registryItems:
  applications:
    - Your_ApplicationName: nq 0
  instances:
    - Your_ApplicationName: 1
  operationNames:
    - Your_ApplicationName:
        - H2/JDBI/Statement/execute
        - "/case/execute"
        - H2/JDBI/Statement/executeUpdate
        - H2/JDBI/Connection/close
        - H2/JDBI/PreparedStatement/executeQuery
segmentItems:
  - applicationCode: Your_ApplicationName
    segmentSize: not null
    segments:
      - segmentId:  not null
        spans:
          - operationName: H2/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_1
              - key: db.statement
                value: SELECT * FROM t_order_0
            startTime:  not null
            endTime:  not null
            componentId: '32'
            componentName: ''
            isError: false
            spanType: Exit
            peer: localhost:-1
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Unknown
            refs:
              - parentEndpointId: 0
                parentEndpoint: "/case/execute"
                networkAddressId: 0
                entryEndpointId: 0
                refType: CrossThread
                parentSpanId: 2
                parentTraceSegmentId: "${Your_ApplicationName[3]}"
                parentServiceInstanceId: 1
                networkAddress: ''
                entryEndpoint: "/case/execute"
                entryServiceInstanceId: 1
            startTime:  not null
            endTime:  not null
            componentId: '60'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
      - segmentId:  not null
        spans:
          - operationName: H2/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_0
              - key: db.statement
                value: SELECT * FROM t_order_1
            startTime:  not null
            endTime:  not null
            componentId: '32'
            componentName: ''
            isError: false
            spanType: Exit
            peer: localhost:-1
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Unknown
            refs:
              - parentEndpointId: 0
                parentEndpoint: "/case/execute"
                networkAddressId: 0
                entryEndpointId: 0
                refType: CrossThread
                parentSpanId: 2
                parentTraceSegmentId: "${Your_ApplicationName[3]}"
                parentServiceInstanceId: 1
                networkAddress: ''
                entryEndpoint: "/case/execute"
                entryServiceInstanceId: 1
            startTime:  not null
            endTime:  not null
            componentId: '60'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
      - segmentId:  not null
        spans:
          - operationName: H2/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_1
              - key: db.statement
                value: SELECT * FROM t_order_1
            startTime:  not null
            endTime:  not null
            componentId: '32'
            componentName: ''
            isError: false
            spanType: Exit
            peer: localhost:-1
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Unknown
            refs:
              - parentEndpointId: 0
                parentEndpoint: "/case/execute"
                networkAddressId: 0
                entryEndpointId: 0
                refType: CrossThread
                parentSpanId: 2
                parentTraceSegmentId: "${Your_ApplicationName[3]}"
                parentServiceInstanceId: 1
                networkAddress: ''
                entryEndpoint: "/case/execute"
                entryServiceInstanceId: 1
            startTime:  not null
            endTime:  not null
            componentId: '60'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
      - segmentId:  not null
        spans:
          - operationName: "/ShardingSphere/parseSQL/"
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Unknown
            tags:
              - key: db.statement
                value: SELECT * FROM t_order
            startTime:  not null
            endTime:  not null
            componentId: '60'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: H2/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '3'
            spanId: '4'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_0
              - key: db.statement
                value: SELECT * FROM t_order_0
            startTime:  not null
            endTime:  not null
            componentId: '32'
            componentName: ''
            isError: false
            spanType: Exit
            peer: localhost:-1
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: '2'
            spanId: '3'
            spanLayer: Unknown
            startTime:  not null
            endTime:  not null
            componentId: '60'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: "/ShardingSphere/JDBCRootInvoke/"
            operationId: '0'
            parentSpanId: '0'
            spanId: '2'
            spanLayer: Unknown
            startTime:  not null
            endTime:  not null
            componentId: '60'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: "/case/execute"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Http
            tags:
              - key: url
                value: http://localhost:{SERVER_OUTPUT_PORT}/shardingsphere-case/case/execute
              - key: http.method
                value: GET
            startTime:  not null
            endTime:  not null
            componentId: '14'
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: '0'
