registryItems:
  applications:
  - {shardingsphere-scenario: nq 0}
  instances:
  - {shardingsphere-scenario: 1}
  operationNames:
  - shardingsphere-scenario: [/case/execute]
  heartbeat: []
segmentItems:
- applicationCode: shardingsphere-scenario
  segmentSize: 5
  segments:
  - segmentId: not null
    spans:
    - operationName: /ShardingSphere/parseSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: db.statement, value: 'SELECT * FROM t_order'}
    - operationName: /ShardingSphere/JDBCRootInvoke/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
    - operationName: /ShardingSphere/parseSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: db.statement, value: 'SELECT i.* FROM t_order o, t_order_item i WHERE o.order_id = i.order_id'}
    - operationName: /ShardingSphere/JDBCRootInvoke/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
  - segmentId: not null
    spans:
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_0"}
      - {key: "db.statement", value: "SELECT * FROM t_order_0"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_0"}
      - {key: "db.statement", value: "SELECT * FROM t_order_1"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
  - segmentId: not null
    spans:
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_1"}
      - {key: "db.statement", value: "SELECT * FROM t_order_0"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_1"}
      - {key: "db.statement", value: "SELECT * FROM t_order_1"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
  - segmentId: not null
    spans:
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_0"}
      - {key: "db.statement", value: "SELECT i.* FROM t_order_0 o, t_order_item_0 i WHERE o.order_id = i.order_id"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_0"}
      - {key: "db.statement", value: "SELECT i.* FROM t_order_1 o, t_order_item_1 i WHERE o.order_id = i.order_id"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
  - segmentId: not null
    spans:
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_1"}
      - {key: "db.statement", value: "SELECT i.* FROM t_order_0 o, t_order_item_0 i WHERE o.order_id = i.order_id"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
    - operationName: Mysql/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 33
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0
      tags:
      - {key: "db.type", value: "sql"}
      - {key: "db.instance", value: "demo_ds_1"}
      - {key: "db.statement", value: "SELECT i.* FROM t_order_1 o, t_order_item_1 i WHERE o.order_id = i.order_id"}
    - operationName: /ShardingSphere/executeSQL/
      operationId: 0
      parentSpanId: 0
      spanId: 0
      spanLayer: null
      startTime: nq 0
      endTime: nq 0
      componentId: 51
      componentName: null
      isError: false
      spanType: Local
      peer: null
      peerId: 0