registryItems:
  applications:
    - Your_ApplicationName: nq 0
  instances:
    - Your_ApplicationName: 1
  operationNames:
    - Your_ApplicationName:
        - "/case/execute"
segmentItems:
  - applicationCode: Your_ApplicationName
    segmentSize: not null
    segments:
      - segmentId: not null
        spans:
          - operationName: "/ShardingSphere/parseSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: not null
            spanLayer: Unknown
            tags:
              - key: db.statement
                value: CREATE TABLE IF NOT EXISTS t_order (order_id BIGINT NOT NULL AUTO_INCREMENT,
                  user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (order_id))
            startTime: not null
            endTime: not null
            componentId: '59'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
