registryItems:
  applications:
    - Your_ApplicationName: nq 0
  instances:
    - Your_ApplicationName: 1
  operationNames:
    - Your_ApplicationName:
        - "/case/execute"
        - Mysql/JDBI/PreparedStatement/executeQuery
segmentItems:
  - applicationCode: Your_ApplicationName
    segmentSize: gt 1
    segments:
      - segmentId: not null
        spans:
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_1
              - key: db.statement
                value: SELECT * FROM t_order_0
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Unknown
            refs:
              - parentEndpointId: 0
                parentEndpoint: "/case/execute"
                networkAddressId: 0
                entryEndpointId: 0
                refType: CrossThread
                parentSpanId: 2
                parentTracesegmentId: not null
                parentServiceInstanceId: 1
                networkAddress: ''
                entryEndpoint: "/case/execute"
                entryServiceInstanceId: 1
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
      - segmentId: not null
        spans:
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_1
              - key: db.statement
                value: SELECT * FROM t_order_1
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Unknown
            refs:
              - parentEndpointId: 0
                parentEndpoint: "/case/execute"
                networkAddressId: 0
                entryEndpointId: 0
                refType: CrossThread
                parentSpanId: 2
                parentTracesegmentId: not null
                parentServiceInstanceId: 1
                networkAddress: ''
                entryEndpoint: "/case/execute"
                entryServiceInstanceId: 1
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
      - segmentId: not null
        spans:
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_1
              - key: db.statement
                value: SELECT i.* FROM t_order_0 o, t_order_item_0 i WHERE o.order_id = i.order_id
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Unknown
            refs:
              - parentEndpointId: 0
                parentEndpoint: "/case/execute"
                networkAddressId: 0
                entryEndpointId: 0
                refType: CrossThread
                parentSpanId: 8
                parentTracesegmentId: not null
                parentServiceInstanceId: 1
                networkAddress: ''
                entryEndpoint: "/case/execute"
                entryServiceInstanceId: 1
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
      - segmentId: not null
        spans:
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_1
              - key: db.statement
                value: SELECT i.* FROM t_order_1 o, t_order_item_1 i WHERE o.order_id = i.order_id
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Unknown
            refs:
              - parentEndpointId: 0
                parentEndpoint: "/case/execute"
                networkAddressId: 0
                entryEndpointId: 0
                refType: CrossThread
                parentSpanId: 8
                parentTracesegmentId: not null
                parentServiceInstanceId: 1
                networkAddress: ''
                entryEndpoint: "/case/execute"
                entryServiceInstanceId: 1
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
      - segmentId: not null
        spans:
          - operationName: "/ShardingSphere/parseSQL/"
            operationId: '0'
            parentSpanId: '0'
            spanId: '1'
            spanLayer: Unknown
            tags:
              - key: db.statement
                value: SELECT * FROM t_order
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '3'
            spanId: '4'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_0
              - key: db.statement
                value: SELECT * FROM t_order_0
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: '2'
            spanId: '3'
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '5'
            spanId: '6'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_0
              - key: db.statement
                value: SELECT * FROM t_order_1
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: '2'
            spanId: '5'
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: "/ShardingSphere/JDBCRootInvoke/"
            operationId: '0'
            parentSpanId: '0'
            spanId: '2'
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: "/ShardingSphere/parseSQL/"
            operationId: '0'
            parentSpanId: '0'
            spanId: '7'
            spanLayer: Unknown
            tags:
              - key: db.statement
                value: SELECT i.* FROM t_order o, t_order_item i WHERE o.order_id = i.order_id
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '9'
            spanId: '10'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_0
              - key: db.statement
                value: SELECT i.* FROM t_order_0 o, t_order_item_0 i WHERE o.order_id = i.order_id
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: '8'
            spanId: '9'
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: Mysql/JDBI/PreparedStatement/executeQuery
            operationId: '0'
            parentSpanId: '11'
            spanId: '12'
            spanLayer: Database
            tags:
              - key: db.type
                value: sql
              - key: db.instance
                value: demo_ds_0
              - key: db.statement
                value: SELECT i.* FROM t_order_1 o, t_order_item_1 i WHERE o.order_id = i.order_id
            startTime: nq 0
            endTime: nq 0
            componentId: '33'
            componentName: ''
            isError: false
            spanType: Exit
            peer: mysql-server:3306
            peerId: '0'
          - operationName: "/ShardingSphere/executeSQL/"
            operationId: '0'
            parentSpanId: '8'
            spanId: '11'
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: "/ShardingSphere/JDBCRootInvoke/"
            operationId: '0'
            parentSpanId: '0'
            spanId: '8'
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: '57'
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: '0'
          - operationName: "/case/execute"
            operationId: '0'
            parentSpanId: "-1"
            spanId: '0'
            spanLayer: Http
            tags:
              - key: url
                value: http://localhost:18080/shardingsphere-case/case/execute
              - key: http.method
                value: GET
            startTime: nq 0
            endTime: nq 0
            componentId: '14'
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: '0'
