registryItems:
  applications:
  - {resttemplate-case: nq 0}
  instances:
  - {resttemplate-case: nq 0}
  operationNames:
  - resttemplate-case: [/resttemplate-case/rest/1, /resttemplate-case/rest/, /sync, '/rest/{id}']
  heartbeat: []
segmentItems:
- applicationCode: resttemplate-case
  segmentSize: 5
  segments:
  - segmentId: not null
    spans:
    - operationName: /resttemplate-case/rest/
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/'}
      - {key: http.method, value: POST}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 13
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
    - operationName: /resttemplate-case/rest/1
      operationId: 0
      parentSpanId: 0
      spanId: 2
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/1'}
      - {key: http.method, value: GET}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 13
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
    - operationName: /resttemplate-case/rest/1
      operationId: 0
      parentSpanId: 0
      spanId: 3
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/1'}
      - {key: http.method, value: PUT}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 13
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
    - operationName: /resttemplate-case/rest/1
      operationId: 0
      parentSpanId: 0
      spanId: 4
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/1'}
      - {key: http.method, value: DELETE}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 13
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:8080
      peerId: 0
    - operationName: /sync
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/resttemplate-case/sync'}
      - {key: http.method, value: GET}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
  - segmentId: not null
    spans:
    - operationName: /rest/
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/'}
      - {key: http.method, value: POST}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /sync, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: '${resttemplate-case[0]}', parentApplicationInstanceId: nq 0, networkAddress: 'localhost:8080', entryServiceName: /sync, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: /rest/{id}
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/1'}
      - {key: http.method, value: GET}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /sync, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 2, parentTraceSegmentId: '${resttemplate-case[0]}', parentApplicationInstanceId: nq 0, networkAddress: 'localhost:8080', entryServiceName: /sync, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: /rest/{id}
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/1'}
      - {key: http.method, value: PUT}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /sync, networkAddressId: 0, entryServiceId: 0,refType: CrossProcess, parentSpanId: 3, parentTraceSegmentId: '${resttemplate-case[0]}', parentApplicationInstanceId: nq 0, networkAddress: 'localhost:8080', entryServiceName: /sync,entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: /rest/{id}
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: url, value: 'http://localhost:8080/resttemplate-case/rest/1'}
      - {key: http.method, value: DELETE}
      logs: []
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /sync, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 4, parentTraceSegmentId: '${resttemplate-case[0]}', parentApplicationInstanceId: nq 0, networkAddress: 'localhost:8080', entryServiceName: /sync, entryApplicationInstanceId: nq 0}
