registryItems:
  applications:
  - {redisson-scenario: nq 0}
  instances:
  - {redisson-scenario: 1}
  operationNames:
  - redisson-scenario: [/redisson/redisson-case]
segmentItems:
- applicationCode: redisson-scenario
  segmentSize: 1
  segments:
  - segmentId: nq 0
    spans:
    - operationName: Redisson/SET
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Cache
      startTime: nq 0
      endTime: nq 0
      componentId: 56
      componentName: 'Redisson'
      isError: false
      spanType: Exit
      peer: '127.0.0.1:6379'
      peerId: 0
      tags:
      - {key: "db.type", value: "Redis"}
    - operationName: /redisson/redisson-case
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/redisson-scenario/redisson/redisson-case'}
      - {key: http.method, value: GET}
