registryItems:
  applications:
  - {rocketMQ-scenario: nq 0}
  instances:
  - {rocketMQ-scenario: 1}
  operationNames:
  - rocketMQ-scenario: [RocketMQ/TopicTest/Producer, /case/rocketMQ-Provider, RocketMQ/TopicTest/Consumer]
segmentItems:
- applicationCode: rocketMQ-scenario
  segmentSize: 2
  segments:
  - segmentId: not null
    spans:
    - operationName: RocketMQ/TopicTest/Producer
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: MQ
      startTime: nq 0
      endTime: nq 0
      componentId: 25
      componentName: ''
      isError: false
      spanType: Exit
      peer: localhost:9876
      peerId: 0
      tags:
      - {key: mq.broker, value: not null }
      - {key: mq.topic, value: TopicTest }
    - operationName: /case/rocketMQ-Provider
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/rocketMQ-provider/case/rocketMQ-Provider'}
      - {key: http.method, value: GET}
  - segmentId: not null
    spans:
    - operationName: RocketMQ/TopicTest/Consumer
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: MQ
      startTime: nq 0
      endTime: nq 0
      componentId: 25
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /case/rocketMQ-Provider, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: '${rocketMQ-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: 'localhost:9876', entryServiceName: /case/rocketMQ-Provider, entryApplicationInstanceId: nq 0}
