registryItems:
  applications:
  - {oracle-scenario: nq 0}
  instances:
  - {oracle-scenario: nq 0}
  operationNames:
  - oracle-scenario: [Oracle/JDBI/Connection/close, Oracle/JDBI/PreparedStatement/executeQuery,
      Oracle/JDBI/PreparedStatement/execute, Oracle/JDBI/Statement/execute, /case/oracle-scenario]
segmentItems:
- applicationCode: oracle-scenario
  segmentSize: 1
  segments:
  - segmentId: not null
    spans:
    - operationName: Oracle/JDBI/Statement/execute
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Database
      startTime: nq 0
      endTime: nq 0
      componentId: 34
      componentName: ''
      isError: false
      spanType: Exit
      peer: oracle-server:1521
      peerId: 0
      tags:
      - {key: db.type, value: sql}
      - {key: db.instance, value: xe}
      - key: db.statement
        value: "CREATE TABLE test_007(\nid VARCHAR(1) PRIMARY KEY, \nvalue VARCHAR(1)\
          \ NOT NULL)"
    - operationName: Oracle/JDBI/PreparedStatement/execute
      operationId: 0
      parentSpanId: 0
      spanId: 2
      spanLayer: Database
      startTime: nq 0
      endTime: nq 0
      componentId: 34
      componentName: ''
      isError: false
      spanType: Exit
      peer: oracle-server:1521
      peerId: 0
      tags:
      - {key: db.type, value: sql}
      - {key: db.instance, value: xe}
      - {key: db.statement, value: 'INSERT INTO test_007(id, value) VALUES(?,?)'}
    - operationName: Oracle/JDBI/PreparedStatement/executeQuery
      operationId: 0
      parentSpanId: 0
      spanId: 3
      spanLayer: Database
      startTime: nq 0
      endTime: nq 0
      componentId: 34
      componentName: ''
      isError: false
      spanType: Exit
      peer: oracle-server:1521
      peerId: 0
      tags:
      - {key: db.type, value: sql}
      - {key: db.instance, value: xe}
      - {key: db.statement, value: 'SELECT id, value FROM test_007 WHERE id=?'}
    - operationName: Oracle/JDBI/PreparedStatement/execute
      operationId: 0
      parentSpanId: 0
      spanId: 4
      spanLayer: Database
      startTime: nq 0
      endTime: nq 0
      componentId: 34
      componentName: ''
      isError: false
      spanType: Exit
      peer: oracle-server:1521
      peerId: 0
      tags:
      - {key: db.type, value: sql}
      - {key: db.instance, value: xe}
      - {key: db.statement, value: 'DROP table test_007'}
    - operationName: Oracle/JDBI/Connection/close
      operationId: 0
      parentSpanId: 0
      spanId: 5
      spanLayer: Database
      tags:
      - {key: db.type,value: sql}
      - {key: db.instance,value: xe}
      - {key: db.statement,value: ''}
      startTime: nq 0
      endTime: nq 0
      componentId: 34
      componentName: ''
      isError: false
      spanType: Exit
      peer: oracle-server:1521
      peerId: 0
    - operationName: /case/oracle-scenario
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/oracle-case/case/oracle-scenario'}
      - {key: http.method, value: GET}
