registryItems:
  applications:
  - {vertx-eventbus-3.x-scenario: 2}
  instances:
  - {vertx-eventbus-3.x-scenario: 1}
  operationNames:
  - vertx-eventbus-3.x-scenario: [
    "/vertx-eventbus-3-scenario/vertx-eventbus/executeTest",
    "/vertx-eventbus-3-scenario/vertx-eventbus/eventbus-case",
    "cluster-message-receiver"
  ]
segmentItems:
- applicationCode: vertx-eventbus-3.x-scenario
  segmentSize: 7
  segments:
  - segmentId: nq 0
    spans:
    - operationName: "#local-message-receiver"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: RPCFramework
      refs:
      - {parentEndpointId: 0, parentEndpoint: "local-message-receiver",
         networkAddressId: 0, entryEndpointId: 0, refType: CrossThread, parentSpanId: 0,
         parentTraceSegmentId: not null, parentServiceInstanceId: 1,
         networkAddress: "", entryEndpoint: "local-message-receiver", entryServiceInstanceId: 1}
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Local
      peer: ""
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "local-message-receiver"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: RPCFramework
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Local
      peer: ""
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "/vertx-eventbus-3-scenario/vertx-eventbus/executeTest"
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Http
      tags:
      - {key: "http.method", value: "GET"}
      - {key: "url", value: "/vertx-eventbus-3-scenario/vertx-eventbus/executeTest"}
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Exit
      peer: not null
      peerId: 0
    - operationName: "/vertx-eventbus-3-scenario/vertx-eventbus/eventbus-case"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      tags:
      - {key: "http.method", value: "GET"}
      - {key: "url", value: "/vertx-eventbus-3-scenario/vertx-eventbus/eventbus-case"}
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Entry
      peer: ""
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "cluster-message-receiver"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: RPCFramework
      refs:
      - {parentEndpointId: 0, parentEndpoint: "cluster-message-receiver",
         networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 0,
         parentTraceSegmentId: not null, parentServiceInstanceId: 1, networkAddress: not null,
         entryEndpoint: "cluster-message-receiver", entryServiceInstanceId: 1}
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Entry
      peer: ""
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "#/vertx-eventbus-3-scenario/vertx-eventbus/executeTest"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      refs:
      - {parentEndpointId: 0, parentEndpoint: "/vertx-eventbus-3-scenario/vertx-eventbus/eventbus-case",
         networkAddressId: 0, entryEndpointId: 0, refType: CrossThread, parentSpanId: 1,
         parentTraceSegmentId: not null, parentServiceInstanceId: 1, networkAddress: "",
         entryEndpoint: "/vertx-eventbus-3-scenario/vertx-eventbus/eventbus-case", entryServiceInstanceId: 1}
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Local
      peer: ""
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "cluster-message-receiver"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: RPCFramework
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Exit
      peer: not null
      peerId: 0
  - segmentId: nq 0
    spans:
    - operationName: "/vertx-eventbus-3-scenario/vertx-eventbus/executeTest"
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      refs:
      - {parentEndpointId: 0, parentEndpoint: "/vertx-eventbus-3-scenario/vertx-eventbus/eventbus-case",
         networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 1,
         parentTraceSegmentId: not null, parentServiceInstanceId: 1,
         networkAddress: "localhost:8080",
         entryEndpoint: "/vertx-eventbus-3-scenario/vertx-eventbus/eventbus-case",
         entryServiceInstanceId: 1}
      tags:
      - {key: "http.method", value: "GET"}
      - {key: "url", value: "/vertx-eventbus-3-scenario/vertx-eventbus/executeTest"}
      startTime: nq 0
      endTime: nq 0
      componentId: 59
      componentName: ""
      isError: false
      spanType: Entry
      peer: ""
      peerId: 0
