registryItems:
  applications:
  - {undertow-scenario: nq 0}
  instances:
  - {undertow-scenario: 1}
  operationNames:
  - undertow-scenario: [/case/undertow, /case/forwardone/,/case/forwardtwo]
segmentItems:
- applicationCode: undertow-scenario
  segmentSize: 3
  segments:
  - segmentId: not null
    spans:
    - operationName: /case/undertow
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 47
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080/case/undertow'}
      - {key: http.method, value: POST}
  - segmentId: not null
    spans:
    - operationName: /case/forwardone/
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 47
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080/case/forwardone/'}
      - {key: http.method, value: GET}
  - segmentId: not null
    spans:
    - operationName: /case/forwardtwo
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 47
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080/case/forwardtwo'}
      - {key: http.method, value: GET}