registryItems:
  applications:
    - {light4j-projectA: nq 0}
  instances:
    - {light4j-projectA: 1}
  operationNames:
    - light4j-projectA: [/v1/data]
segmentItems:
  - applicationCode: light4j-projectA
    segmentSize: nq 0
    segments:
      - segmentId: not null
        spans:
          - operationName: /v1/data
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 49
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/v1/data'}
              - {key: http.method, value: GET}