registryItems:
  applications:
    - {spring-async-scenario: nq 0}
  instances:
    - {spring-async-scenario: 1}
  operationNames:
    - spring-async-scenario: [/spring-async/spring-async-case, /]
  heartbeat: []
segmentItems:
  - applicationCode: spring-async-scenario
    segmentSize: 3
    segments:
      - segmentId: nq 0
        spans:
          - operationName: /spring-async/spring-async-case
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 14
            componentName: ''
            isError: false
            spanType: Entry
            peer: ''
            peerId: 0
            tags:
              - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/spring-async-case/spring-async/spring-async-case'}
              - {key: http.method, value: GET}
      - segmentId: nq 0
        spans:
          - operationName: /
            operationId: 0
            parentSpanId: 0
            spanId: 1
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 2
            componentName: ''
            isError: false
            spanType: Exit
            peer: skywalking.apache.org:80
            peerId: 0
            tags:
              - {key: url, value: 'http://skywalking.apache.org/?k=v'}
              - {key: http.method, value: GET}
          - operationName: SpringAsync
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: 65
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: 0
            refs:
              - {parentEndpointId: 0, parentEndpoint: /spring-async/spring-async-case, networkAddressId: 0,
                 entryEndpointId: 0, refType: CrossThread, parentSpanId: 0, parentTraceSegmentId: '${spring-async-scenario[0]}',
                 parentServiceInstanceId: 1, networkAddress: '', entryEndpoint: /spring-async/spring-async-case,
                 entryServiceInstanceId: 1}
      - segmentId: nq 0
        spans:
          - operationName: /
            operationId: 0
            parentSpanId: 0
            spanId: 1
            spanLayer: Http
            startTime: nq 0
            endTime: nq 0
            componentId: 2
            componentName: ''
            isError: false
            spanType: Exit
            peer: skywalking.apache.org:80
            peerId: 0
            tags:
              - {key: url, value: 'http://skywalking.apache.org/?k=v'}
              - {key: http.method, value: GET}
          - operationName: SpringAsync
            operationId: 0
            parentSpanId: -1
            spanId: 0
            spanLayer: Unknown
            startTime: nq 0
            endTime: nq 0
            componentId: 65
            componentName: ''
            isError: false
            spanType: Local
            peer: ''
            peerId: 0
            refs:
              - {parentEndpointId: 0, parentEndpoint: /spring-async/spring-async-case, networkAddressId: 0,
                 entryEndpointId: 0, refType: CrossThread, parentSpanId: 0, parentTraceSegmentId: '${spring-async-scenario[0]}',
                 parentServiceInstanceId: 1, networkAddress: '', entryEndpoint: /spring-async/spring-async-case,
                 entryServiceInstanceId: 1}
