registryItems:
  applications:
  - {canal-scenario: nq 0}
  instances:
  - {canal-scenario: nq 0}
  operationNames:
  - canal-scenario: [/case/canal-case, Canal/example]
  heartbeat: []
segmentItems:
- applicationCode: canal-scenario
  segmentSize: 1
  segments:
  - segmentId: nq 0
    spans:
    - operationName: Canal/example
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 54
      componentName: ''
      isError: false
      spanType: Exit
      peer: not null
      peerId: 0
      tags:
      - {key: batchSize, value: '1000'}
      - {key: destination, value: example}
    - operationName: /case/canal-case
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/canal-scenario/case/canal-case'}
      - {key: http.method, value: GET}
